// Code generated by hertz generator.

package user

import (
	user "api/biz/model/user"
	rpcClient "api/biz/rpc"
	"api/pkg/constants"
	"api/pkg/mw"
	"api/pkg/response"
	"common-components/errno"
	"common-components/logger"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/jinzhu/copier"
	rpcUser "rpc/kitex_gen/user"
)

// UserIndex .
// @router /douyin/user/ [GET]
func UserIndex(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserIndexRequest
	err = c.BindAndValidate(&req)
	if logger.CheckError(err, "UserIndexRequest BindAndValidate Failed") {
		c.JSON(consts.StatusBadRequest, errno.ConvertErr(err))
		return
	}
	v, _ := c.Get(constants.IdentityKey)
	params := rpcUser.UserIndexRequest{
		UserId:   req.UserID,
		MyUserId: v.(*rpcUser.User).Id,
	}
	User, err := rpcClient.UserIndex(context.Background(), &params)
	if logger.CheckError(err, "rpcClient.UserClient.UserIndex Failed") {
		response.SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	response.SendResponse(c, errno.Success, User)
}

// UserRegister .
// @router /douyin/user/register/ [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if logger.CheckError(err, "RegisterRequest BindAndValidate Failed") {
		c.JSON(consts.StatusBadRequest, errno.ConvertErr(err))
		return
	}
	params := rpcUser.RegisterRequest{}
	_ = copier.Copy(params, req)
	err = rpcClient.UserRegister(context.Background(), &params)
	if logger.CheckError(err, "rpcClient.UserClient.UserRegister Failed") {
		response.SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	response.SendResponse(c, errno.Success, nil)
}

// UserLogin .
// @router /douyin/user/login/ [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {
	mw.JwtMiddleware.LoginHandler(ctx, c)
}
