// Code generated by Kitex v0.7.2. DO NOT EDIT.

package videoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	video "rpc/kitex_gen/video"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	VideoFeed(ctx context.Context, request *video.VideoFeedRequest, callOptions ...callopt.Option) (r *video.VideoFeedResponse, err error)
	VideoPublish(ctx context.Context, request *video.VideoPublishRequest, callOptions ...callopt.Option) (r *video.VideoPublishResponse, err error)
	PublishList(ctx context.Context, request *video.PublishListRequest, callOptions ...callopt.Option) (r *video.PublishListResponse, err error)
	GetVideoInfo(ctx context.Context, request *video.GetVideoInfoRequest, callOptions ...callopt.Option) (r *video.GetVideoInfoResponse, err error)
	GetManyVideoInfos(ctx context.Context, request *video.GetManyVideoInfosRequest, callOptions ...callopt.Option) (r *video.GetManyVideoInfosResponse, err error)
	AddVideoFavoriteCount(ctx context.Context, request *video.AddVideoFavoriteCountRequest, callOptions ...callopt.Option) (r *video.AddVideoFavoriteCountResponse, err error)
	SubVideoFavoriteCount(ctx context.Context, request *video.SubVideoFavoriteCountRequest, callOptions ...callopt.Option) (r *video.SubVideoFavoriteCountResponse, err error)
	AddVideoCommentCount(ctx context.Context, request *video.AddVideoCommentCountRequest, callOptions ...callopt.Option) (r *video.AddVideoCommentCountResponse, err error)
	SubVideoCommentCount(ctx context.Context, request *video.SubVideoCommentCountRequest, callOptions ...callopt.Option) (r *video.SubVideoCommentCountResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) VideoFeed(ctx context.Context, request *video.VideoFeedRequest, callOptions ...callopt.Option) (r *video.VideoFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VideoFeed(ctx, request)
}

func (p *kVideoServiceClient) VideoPublish(ctx context.Context, request *video.VideoPublishRequest, callOptions ...callopt.Option) (r *video.VideoPublishResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VideoPublish(ctx, request)
}

func (p *kVideoServiceClient) PublishList(ctx context.Context, request *video.PublishListRequest, callOptions ...callopt.Option) (r *video.PublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishList(ctx, request)
}

func (p *kVideoServiceClient) GetVideoInfo(ctx context.Context, request *video.GetVideoInfoRequest, callOptions ...callopt.Option) (r *video.GetVideoInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoInfo(ctx, request)
}

func (p *kVideoServiceClient) GetManyVideoInfos(ctx context.Context, request *video.GetManyVideoInfosRequest, callOptions ...callopt.Option) (r *video.GetManyVideoInfosResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetManyVideoInfos(ctx, request)
}

func (p *kVideoServiceClient) AddVideoFavoriteCount(ctx context.Context, request *video.AddVideoFavoriteCountRequest, callOptions ...callopt.Option) (r *video.AddVideoFavoriteCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddVideoFavoriteCount(ctx, request)
}

func (p *kVideoServiceClient) SubVideoFavoriteCount(ctx context.Context, request *video.SubVideoFavoriteCountRequest, callOptions ...callopt.Option) (r *video.SubVideoFavoriteCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SubVideoFavoriteCount(ctx, request)
}

func (p *kVideoServiceClient) AddVideoCommentCount(ctx context.Context, request *video.AddVideoCommentCountRequest, callOptions ...callopt.Option) (r *video.AddVideoCommentCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddVideoCommentCount(ctx, request)
}

func (p *kVideoServiceClient) SubVideoCommentCount(ctx context.Context, request *video.SubVideoCommentCountRequest, callOptions ...callopt.Option) (r *video.SubVideoCommentCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SubVideoCommentCount(ctx, request)
}
