// Code generated by hertz generator.

package message

import (
	"context"

	message "api/biz/model/message"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// MessageList .
// @router /douyin/message/action/ [POST]
func MessageList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req message.MessageListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(message.MessageListResponse)

	c.JSON(consts.StatusOK, resp)
}

// ChatAction .
// @router /douyin/message/chat/ [GET]
func ChatAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req message.ChatActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(message.ChatActionResponse)

	c.JSON(consts.StatusOK, resp)
}
