// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	comment "api/biz/router/comment"
	favorite "api/biz/router/favorite"
	message "api/biz/router/message"
	relation "api/biz/router/relation"
	user "api/biz/router/user"
	video "api/biz/router/video"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	comment.Register(r)

	favorite.Register(r)

	message.Register(r)

	relation.Register(r)

	video.Register(r)

	user.Register(r)
}
