// Code generated by hertz generator.

package user

import (
	"api/pkg/mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userindexMw() []app.HandlerFunc {
	// your code...
	// 创建一个中间件切片
	middlewares := []app.HandlerFunc{
		// 添加身份验证中间件
		mw.AuthenticationMiddleware(),
	}
	return middlewares
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}
